### PR TITLE
Create unique filenames for each run with logpyle

### PR DESCRIPTION
**Pull request by matthiasdiener**
Unique (`u`) mode adds a timestamp to the filename automatically, synchronized across ranks.

before: `prediction-rank0.sqlite`, `prediction-rank1.sqlite`, ...
after: `prediction-rank0-20230220-234917.sqlite`, `prediction-rank1-20230220-234917.sqlite`, ...

### CODE REVIEW

**Comment by matthiasdiener** [comment]
@MTCam would this interfere with automatic performance tracking?

**Comment by MTCam** [comment]
> @MTCam would this interfere with automatic performance tracking?

Yeah, but I like this.  We should fix up the timing procedure so that it accounts for the timestamps.

**Comment by anderson2981** [comment]
This is fine by me. I'll wait until Mike is ready to integrate it with the timing scripts

**Review by anderson2981 — APPROVED** [review]

**Comment by MTCam** [comment]
> This is fine by me. I'll wait until Mike is ready to integrate it with the timing scripts

I think it'll be ok to merge and fix up any issues as we encounter them. 

 I'll have to figure out how to fix it here:
https://github.com/illinois-ceesd/timing/blob/0c60efa8d40341f0a3b8449873eac1bbd561a4b2/run-driver-timing.sh#L185

... and if we plan on making this change in other timed drivers, then in these scripts for isolator, nozzle, and flame1d:

https://github.com/illinois-ceesd/timing/blob/0c60efa8d40341f0a3b8449873eac1bbd561a4b2/time-lazy-isolator.sh#L156

I guess it would be best to make it agnostic to the timestamp.  Trouble could ensue if there end up being sqlite files from multiple runs in the location where I'm trying to find these files.  Any advice?

**Comment by matthiasdiener** [comment]
> I guess it would be best to make it agnostic to the timestamp. Trouble could ensue if there end up being sqlite files from multiple runs in the location where I'm trying to find these files. Any advice?

Would it be an option just to remove any `*.sqlite` files before each run to make sure there is only one after the run to analyze?

**Pull request closed without merging**
